### ISSUE TITLE
Environment Error

### ISSUE THREAD

**Issue by steveharwell1** [wagtail/Willow#86] opened 2020-09-06 20:30 UTC
Hi,
I'm having trouble installing Wagtail on my Raspberrypi 4.
When I try to install it, I get an Environment Error for willow.

Bellow is a print out of trying to install willow by itself on the same system.

I am using a fresh virtual environment where I have only run ```pip install wagtail```

```
(env) pi@raspberrypi:~/Dev/wagtail_start $ pip install willow
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting willow
Could not install packages due to an EnvironmentError: 404 Client Error: Not Found for url: https://www.piwheels.org/simple/willow/
```

**Comment by gasman** [comment] 2022-02-21 14:41
This looks like an issue with the piwheels repo rather than Willow (possibly a duplicate of https://github.com/piwheels/piwheels/issues/63?), and the failing URL is returning a response now.

**Closed by gasman** 2022-02-21 14:41 UTC
