### ISSUE TITLE
ValueError Image has wrong mode when accessing renditions of this particular image.

### ISSUE THREAD

**Issue by salty-ivy** [wagtail/Willow#154] opened 2024-09-12 19:59 UTC
## Description 
On a successful upload of this image, it bypasses the image rendition generation.

and on web when trying to access this via CMS admin we get  a `ValueError`   and  `image has wrong mode`  down from willow/pillow as wagtail tries to regenerate the renditions if not found.

<img width="1148" alt="Screenshot 2024-09-12 at 10 32 26 PM" src="https://github.com/user-attachments/assets/a6d7b2fd-bb1c-4810-8b22-9737d1d30e91">

after  deleting the `wagtail.images.Image` instance and corresponding renditions it seems to work.

## the Image

![tony_bern](https://github.com/user-attachments/assets/c3c76464-ac61-4a40-9dea-54ba34b60d98)

## Ideas and thoughts

Whole page `/admin/images/` becomes  inaccessible which is a big issues cause there's no warning at the time of upload.

**May be wagtail/willow should throw some error/warning or reject the upload if renditions don't get generated on upload?**

**Comment by Stormheg** [comment] 2024-09-13 15:10
I tried uploading this file and can confirm I'm seeing the same error (`Willow==1.8.0` and `wagtail==6.2.1`)

**Comment by Stormheg** [comment] 2024-09-13 16:00
I've investigated and this is an issue upstream in Pillow 10.3.0. There is an issue open about it already and I've commented on it with my findings here: https://github.com/python-pillow/Pillow/issues/8333#issuecomment-2349279247

Let's wait and see what happens.

---

As a workaround you can install `Pillow=10.2.0` in the mean time.

**Comment by salty-ivy** [comment] 2024-09-14 22:50
@Stormheg thanks!

**Comment by Stormheg** [comment] 2024-10-26 15:24
The issue is fixed in Pillow 11.0, which is not currently supported by Willow. I created https://github.com/wagtail/Willow/pull/158 for that.

I suggest we keep this open until https://github.com/wagtail/Willow/pull/158 is merged and released.

**Comment by zerolab** [comment] 2024-10-26 22:06
https://github.com/wagtail/Willow/releases/tag/v1.9.0 is now out, so closing this

**Closed by zerolab** 2024-10-26 22:06 UTC
Labels: bug
